### ISSUE TITLE
desktop-autostart and user-basic-dev bundles cause install to fail

### ISSUE THREAD

**Issue by danboid** [clearlinux/clr-installer#224]
desktop-autostart is one of the auto-selected/default bundles selected when doing a default install of Clear Linux yet, on my laptop at least, the installation never completes because the installer/swupd progress bar enters an infinite loop when supposedly installing desktop-autostart.

When the installer says desktop-autostart is being installed, the progress bar fills and then empties and does so on loop and it never progresses to installing the next bundle. To get Clear Linux to install at all, I had to unselect the desktop-autostart bundle but I was able to successfully install desktop-autostart using swupd post install.

The same thing happens if you try to install user-basic-dev as one of your initial bundles - its progress bar just gets stuck in a loop and the install never completes. This is less of a hazard as it isn't selected by default.

**Comment by danboid** [comment]
In the case of user-basic-dev, I think I might've just been too impatient. The bundle menu gives you no idea of the size of the bundles nor how many or what programs are included in that bundle and it would seem, now that I'm installing it from the terminal, that user- basic-dev is quite the epic!

**Comment by danboid** [comment]
user-basic-dev has installed now but it took about an hour on my 100Mb connection. 

"basic-dev" is understating its contents a bit IMO ;)

**Comment by mdhorn** [comment]
@danboid These appear to be that they would have completed but took a very long time.

The current status bar is really more of a "horizontal spinner" rather than a true progress bar. Currently, swupd (our package managing tool) cannot supply the needed information for a true progress bar in the installer.

We are tracking a change for this once the swupd change is implemented:
https://github.com/clearlinux/clr-installer/issues/12

When the original status bar was implemented we were hoping that the update to swupd would be easily done, but that has not been the case.

There are several pending suggesting for the UI of the installer, and we may consider switching to a more standard spinner to alleviate confusion on this. But we will track that outside of this Issue.

I'm closing this Issue since the progress was slow, but does reach a conclusion.

**Comment by DevAspirerKlaus** [comment]
A little suggestion: the installer steps could have some kind of "expande/collapse" (more detailed) view.  That way we could be less anxious knowing that installation is still running.
