### ISSUE TITLE
Enable clr-installer support in published PXE images

### ISSUE THREAD

**Issue by mdhorn** [clearlinux/clr-installer#247]
As someone who deploys Clear Linux OS on many targets, I would like to use clr-installer instead of ister as the installation mechanism.

Currently, the PXE images published on https://download.clearlinux.org/current/ still use ister.py.

**Comment by chenming1986** [comment]
A few tips to make clr-installer work with pxe boot based on current installer.img. I can help on basic verification with my iPXE setup if needed.
### iPXE setup
https://clearlinux.org/documentation/clear-linux/guides/network/ipxe-install

### kernel
use the kernel in installer.img

### kernel cmdline
copy the command line from installer.img, remove `root` and `rootfstype` parameters since we don't want to mount the real disk at this time, and add `root=/dev/ram clri.descriptor=http://192.168.1.1/clr-installer.yaml` to the cmdline. `root=/dev/ram` is neccessary, otherwise a few services and clr-installer itself will fail due to not able to write temp/configuration files

### initrd
include all the contents from the root partition of installer.img, create a symlink in the root of initrd with the name **init** and link it to **/usr/lib/systemd/systemd**, add `ExecStartPre=/usr/bin/sleep 10` to the **Service** section in **/usr/lib/systemd/system/clr-installer.service** (this is just a workaround since currently clr-installer may start before the network is ready and it will fail to fetch the installation descriptor file via network)

### iPXE configuration file
The file may look like
```
#!ipxe
kernel linux quiet console=tty0 console=ttyS0,115200n8 initrd=initrd root=/dev/ram init=/usr/bin/initra-desktop initcall_debug tsc=reliable no_timer_check noreplace-smp kvm-intel.nested=1 intel_iommu=igfx_off cryptomgr.notests rcupdate.rcu_expedited=1 rcu_nocbs=0-64 rw nomodeset i915.modeset=0 clri.descriptor=http://192.168.1.1/clr-installer.yaml
initrd initrd
boot
```

**Comment by qzheng527** [comment]
Thanks Ming for the sharing, it works!
My understanding is that the released PXE image should contain the clr-installer and make it boot automatically just like it is in  the intaller image.
Who is the owner of generating the PXE image? Many internal customers really requires this install method.

**Comment by mdhorn** [comment]
@qzheng527  Making updates to the PXE images to use the new clr-installer instead of ister is on the roadmap, but the core installer team right now is focused on the creation of a graphical interface for the clr-installer. We maybe not start on this for a month or two.

But as this is open source, we welcome pull requests for such changes!

**Comment by amygilliam1** [comment]
@chenming1986 , we will be implementing this request around the end of July 2019.

**Comment by jwakre** [comment]
PXE image support was added in release 2.3.3.

PXE images are generated for Clear versions 31770 and later. The latest generated PXE images can be found at: https://clearlinux.org/downloads

**Comment by ionutnechita** [comment]
Hi Clear Linux Team,

If we can increase the time for clr-installer-provision.service, would help me.
ExecStartPre=/usr/bin/sleep 10 -> ExecStartPre=/usr/bin/sleep 30
1. My DHCP server is slower.
2. The interface didn't start up fast for vm using vmware esxi.
