### ISSUE TITLE
Indicate the current installation phase during installation

### ISSUE THREAD

**Issue by abecastillo** [clearlinux/clr-installer#283]
**Is your feature request related to a problem? Please describe.**
There are multiple phases during the installation process. Regardless specific/more-accurate details on the process (https://github.com/clearlinux/clr-installer/issues/12) knowing the current phase of the installation process gives the user an idea of how far in the process he/she currently is.

**Describe the solution you'd like**
A series of messages is displayed based on the installation process: 
(sample phases titles I could get while I installed it)
"Phase 1/7 : partition setup"
"Phase 2/7 : ...configuration..."
"Phase 3/7 : ...mapping..."
"Phase 4/7 : writing ext4 file system to nvme"
"Phase 5/7 : writing mount file"
"Phase 6/7 : installing the base system"
"Phase 7/7 : installation complete"

**Describe alternatives you've considered**

**Additional context**
Used clear-28740-live-desktop-beta.img

**Comment by mdhorn** [comment]
Thank you for your feedback on this.

We intentionally avoid the method of on step X of Y because the steps are never close to being equally weighted (from a time perspective).

Now that we are using a single swupd command to install all bundles at once, this process is considerably quicker than the previous releases.

Once the new swupd is release (hopefully in the very near future) we are ready with an update that greatly improves the feedback to the user from issue #12.

In the future, if swupd can provide an accurate estimate of the amount of data to be downloaded, we may consider adding an overall time estimate based on network speed to the swupd URL and the sizes.
