### ISSUE TITLE
Missing initrd from /usr/lib/kernel/initrd.org.clearlinux.native.xxx

### ISSUE THREAD

**Issue by LibertadCruz** [clearlinux/clr-installer#418]
**Describe the bug**
I believe that the installer needs to add initrd.org.clearlinux.native.XXXX

**Comment by mdhorn** [comment]
@LibertadCruz We need more information here.
What error are you seeing?
What image are you referencing? Are you referring to a generated image or an installed system?

**Comment by miguelinux** [comment]
Hi @mdhorn,
As the installer is using an `initrd` you need to add some kenrel modules.
They are not built-in into the kernel as they represent a delay on boot.

We are using those modules currently  when you use an encrypted rootfs.

Currently this missing of ATKB drivers is affecting the following issue: 
https://github.com/clearlinux/distribution/issues/796

**Comment by miguelinux** [comment]
As an example of my laptop has:

```
$ cat /proc/cmdline
initrd=\EFI\org.clearlinux\initrd-org.clearlinux.native.5.0.18-767 initrd=\EFI\org.clearlinux\freestanding-clr-init.cpio.gz root=UUID=c126690a-d905-41b1-933b-56aaab2e6dfb rd.luks.uuid=8796afd4-111b-44d8-8f61-dc9424d5695d quiet console=tty0 console=ttyS0,115200n8 init=/usr/bin/initra-desktop  initcall_debug tsc=reliable no_timer_check noreplace-smp kvm-intel.nested=1 rootfstype=ext4,btrfs,xfs intel_iommu=igfx_off cryptomgr.notests rcupdate.rcu_expedited=1 rcu_nocbs=0-64 rw log_buf_len=1M
```
The `systemd-boot` config file is as
```
/boot/loader/entries # cat Clear-linux-native-5.0.18-767.conf
title Clear Linux OS
linux /EFI/org.clearlinux/kernel-org.clearlinux.native.5.0.18-767
initrd /EFI/org.clearlinux/initrd-org.clearlinux.native.5.0.18-767
initrd /EFI/org.clearlinux/freestanding-clr-init.cpio.gz
options root=UUID=c126690a-d905-41b1-933b-56aaab2e6dfb rd.luks.uuid=8796afd4-111b-44d8-8f61-dc9424d5695d quiet console=tty0 console=ttyS0,115200n8 init=/usr/bin/initra-desktop  initcall_debug tsc=reliable no_timer_check noreplace-smp kvm-intel.nested=1 rootfstype=ext4,btrfs,xfs intel_iommu=igfx_off cryptomgr.notests rcupdate.rcu_expedited=1 rcu_nocbs=0-64 rw log_buf_len=1M
```

**Comment by mdhorn** [comment]
@miguelinux @evil-brain  Let's meet to discuss this and other initrd pending concerns

**Comment by evil-brain** [comment]
I've read the other issue, but I don't think the problem lies with the LiveCD's initrd.

The LiveCD's initrd has no user interaction (other than initrd echos status to /dev/tty0 and /dev/kmsg), it runs a system check -> searches for and mounts the device with the rootfs -> mounts and overlays rootfs -> switch_root to the new rootfs.

The _init_ script can be found here: https://github.com/clearlinux/clr-installer/blob/master/iso_templates/initrd_init_template

The source that builds initrd is found here: https://github.com/clearlinux/clr-installer/blob/master/isoutils/isoutils.go (it just uses swupd to install os-core, and copies basic filesystem drivers)

I tested booting on an AMDGPU system and everything works as expected, first the system uses the EFI VGA FB, once the initrd is done, then the system loads amdgpu and boots normally to graphics. 

initrd on the LIveCD is a minimal configuration just to verify system compatibility, deal with sqashfs rootfs, and launch the normal init process. Udev handles initializing and loading drivers after that point, and that should be equivalent to a regular Clear boot.

Based on the latest feedback, it appears the mouse/keyboard issue may be unique to this user, and I haven't heard any feedback about Logitech USB devices malfunctioning on the LIveCD.

FWIW from https://cateee.net/lkddb/web-lkddb/HID_LOGITECH_DJ.html, that Logitech device should be handled by USB_HID if the driver fails to load, the only thing affected is multiple mice/keyboards bound to one RX... it just multiplexes them all as one device, but should still "work"

As an aside, we still are publishing the old .img files. If you suspect initrd or the ISO pieces are a problem, try the .img file instead.
An example link: https://download.clearlinux.org/releases/current/clear/clear-29880-live-desktop.img.xz

**Comment by mdhorn** [comment]
After our discussion this week, there are no initrd changes needed for the ISO images.
