### ISSUE TITLE
Support insecure HTTP mirror

### ISSUE THREAD

**Issue by jwakre** [clearlinux/clr-installer#478]
**Describe the solution you'd like**
HTTP mirror support should be enabled when the user acknowledges that the install may be insecure. HTTP support must enabled with an extra step, like a checkbox or flag that notifies the user that the mirror may be insecure.

**Comment by reaganlo** [comment]
Instead of a checkbox it could be a popup message dialog with two buttons (Yes, No).

**Comment by mdhorn** [comment]
Besides the User Interface for acknowledging the use of HTTP, we need to add a command-line argument so that one can build images using an HTTP URL. This would be need for such things a building from a local developer mix.

Consider using the same flag as swupd
`--allow-insecure-http`     `Allow updates over insecure connections`

**Comment by mdhorn** [comment]
Once an insecure connection is confirmed, we should create a local swupd configuration file to retain the option:
```
cat /etc/swupd/config
[GLOBAL]
# Allow updates over insecure connections
allow_insecure_http=true
```

To ensure this propagates to the target system, the installer should copy the contents of /etc/swupd to the target system similar to what is done for the network settings.
