### ISSUE TITLE
Would be nice to have "Check integrity of installer" option prior to starting it

### ISSUE THREAD

**Issue by bktan8** [clearlinux/clr-installer#490]
It would be nice to have the ability to run an integrity check of the installer.  I know you can do a checksum of the image itself, but having ability to check the actual bits that's been burned to a device would be great.  Have this as a menu item at the systemd boot menu.

**Comment by lebensterben** [comment]
>It would be nice to have the ability to run an integrity check of the installer.  I know you can do a checksum of the image itself, but having ability to check the actual bits that's been burned to a device would be great.  Have this as a menu item at the systemd boot menu.  

@bktan8

It seems unnecessary to me to have this integrity check.

A checksum could make sure that the live image you downloaded is not compromised. And when you burn the live image with `dd` command, it's very unlikely that the burned image is different from the is file. Because `dd` is making byte-to-byte copies.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by karthikprabhuvinod** [comment]
@lebensterben Good point. However, if there are hiccups during the generation process, it could leave a bad image which is not really bootable. There is no way of knowing that unless we have a source media integrity check.

**Comment by mdhorn** [comment]
Fixed in clr-installer 2.6.1, Clear Linux OS 33300 or higher.
