### ISSUE TITLE
Desktop installer freezes and server installer crashes during "downloading missing files"

### ISSUE THREAD

**Issue by NOVAinc** [clearlinux/clr-installer#510]
**Describe the bug**
Both the graphical installer and the CL installer fail to install the system.

**To Reproduce**

I don't know how to reproduce it on other systems.. this is what I did

1. Launch the installer by booting into the live USB, which I burned following the instructions found in the clear linux website.
2. Fill the required fields for the installation to become available, as well as choosing a wifi network. I tried changing the setting for my use case (spanish language, latinamerican keyboard layout, time zone etc) and also tried using the default ones. No bundles were selected.
3. Select safe installation, using unallocated space in the disk.
4. Proceed to install.
5. The installer creates the partitions necessary, goes on to download missing files and freezes during this step. 

I tried leaving the graphical installer overnight and it stayed stuck. The command line installer gets stuck for 10 minutes and then throws an error with instructions to report the issue here, together with both attached files.

**Expected behavior**
The installer should install the OS on the system

**Screenshots**
https://drive.google.com/file/d/0BwvbCaUXVrM8SVJiWTY0LUJsVWVnSVliejJKc01uQUJCQmNN/view?usp=sharing

**Environment (please complete the following information):**
 - Clear Linux OS Version: 30970
 - Installer Version: 2.1.1
 - Platform: i5 5200u laptop. 8gb of ddr3 ram. 1tb hard drive.

**Additional context**
I don't know if any additional information might be of help. The system requirements check was succesful and UEFI was enabled. Let me know how I can help fix this issue. I've been wanting to try Clear for a while and I'm sad I can't install it. I can run it on a VM using virtualbox with ubuntu 18.04.3 as host system on the same laptop.

**Attached files**
I don't see an option to attach files here, so I uploaded them to google drive

pre-install-clr-installer.yaml
https://drive.google.com/open?id=1NB85hPd_vL-M_XOT2RY0Z-lhAjnKKBNa

clr-installer.log
https://drive.google.com/open?id=1OZn1zlcf7aT5a1YcWilCFKfbHdzuRahX

UPDATE: I added a picture of the error screen.

**Comment by mdhorn** [comment]
@NOVAinc Thank you for the bug report.

The problem here is a bug from the improper sorting of the partitions.

The disk you were using already had 8 partitions.  We could reuse the existing swap, but needed to add Clear Linux's /boot and /. The partitions were added as 9 and 10. We have some login that is dependent upon having the partitions properly sorted, but due to a sorting bug they were ordered as sda1, sda**10**, sda2, sda3, sda4, sda5, sda6, sda7, sda8, sda9.
This resulted in trying to install the OS in the small partition for created for boot.

For now, you can save remove the two newly created partitions sda9 and sda10.

We will need to replace a bug fix for this sorting problem.

We are trying to get a release out the door this week which enabled Advanced Disk Partitioning (see #410) which you could use to safely install on your existing disk if we don't get this bug fixed in the immediate release.

**Comment by NOVAinc** [comment]
@mdhorn thanks for the swift response. When would this happen? So I know when to download the new release and retry.

**Comment by mdhorn** [comment]
@NOVAinc The new version of the installer which has the Advanced Disk configuration was release in Clear Linux* OS 31030. You can [download the installation ISO](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz) here:
https://clearlinux.org/downloads

**Comment by NOVAinc** [comment]
> @NOVAinc The new version of the installer which has the Advanced Disk configuration was release in Clear Linux* OS 31030. You can [download the installation ISO](https://cdn.download.clearlinux.org/releases/31030/clear/clear-31030-live-desktop.iso.xz) here:
> https://clearlinux.org/downloads

Thank you for the update
