### ISSUE TITLE
Swupd Errors on Fresh Install

### ISSUE THREAD

**Issue by dedguy21** [clearlinux/clr-installer#528]
Downloaded clear server iso yesterday 9-17-19

During install swupd threw errors and didn't download necessary packages. 

I tried twice, both time swupd errors. 

Bare metal install, unable to capture screen. And unable to print log.

**Comment by jwakre** [comment]
The installer should write a log at `/root/clr-installer.log`

**Comment by mdhorn** [comment]
@dedguy21 In order for us to provide any sort of useful help, we need more information:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**
 - Clear Linux OS Version: [swupd info]
 - Installer Version [clr-installer -v]
 - Platform: [hardware infomation]


**Additional context**
Add any other context about the problem here.

**Comment by dedguy21** [comment]
Downloaded a new iso today. Didn't have any errors
