### ISSUE TITLE
No way to encrypt server install

### ISSUE THREAD

**Issue by treeshateorcs** [clearlinux/clr-installer#541]
**Describe the bug**
There is no way to choose "enable encryption" in the server installer

**To Reproduce**
1. run clr-installer
2. click "configure installation media
3. click "enable encryption"
4. after entering a password "advanced installation" is automatically ticked and "enable encryption" is unticked and greyed out

**Expected behavior**
"enable encryption" should be ticked

**Screenshots**
![image](https://user-images.githubusercontent.com/44036082/65569521-99b5d680-df66-11e9-8cdb-eed2beebfff4.png)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31080
 - Installer Version 2.2.0
 - Platform: Thinkpad T450s and qemu x86

**Comment by treeshateorcs** [comment]
even if I add CLR_BOOT, CLR_SWAP and CLR_ROOT I am unable to check "enable encryption"

**Comment by treeshateorcs** [comment]
this is a regression, v2.1.1 works fine

**Comment by mdhorn** [comment]
@treeshateorcs Thank you for raising this issue.

The replacement for Advanced Disk Config (ADC) in the text-based installer was a compromise to enable a majority feature in both the text-based and graphical installers.
Support for encrypted file systems under ADC was excluded initially due to some complexities around supporting re-use which we are tracking in #512 

The next planned step around storage is a refactor to make the code more maintainable and easier to enable additional features like LVM and encryption under ADC. 

What specific use case were you trying to use encryption with ADC?
We may be able to allow the "Enable Encryption" checkbox to at least make the root file system encrypted under ADC in the short-term; would this meet your immediate needs?

**Comment by treeshateorcs** [comment]
i don't understand why it doesn't work in the TUI installer, but works in the GUI installer. also I wasn't using ADC it is automatically checked after entering a password and confirmation, no matter what method was checked before that

**Comment by mdhorn** [comment]
@treeshateorcs Thank you for the clarification.
This is a bug and we should have it addressed in a release later this week or early next week at the latest.

**Comment by mdhorn** [comment]
Fixed in clr-installer release 2.3.0 available in Clear Linux OS since 31150
