### ISSUE TITLE
Lack of an option to install without a boot loader 

### ISSUE THREAD

**Issue by chdslv** [clearlinux/clr-installer#584]
Could it be possible to have an option not to install the boot loader? From what I get from reading the forums, the CLR_BOOT would overwrite the EFI partition. Or, can the boot loader just add a boot folder to exiting EFI partition?

What I can understand from the forum posts, that one has to reinstall Windows after installing Clear Linux. And, add EFI folders of other Linux distros. Reinstalling distro/OS is out of question. Can the installer see other installed distros/OSs and place them correctly, as in Grub?

**Comment by mdhorn** [comment]
@chdslv Currently, the installer does not handle booting options, we rely on clr-boot-manager.

Using Advanced Partitioning, adding the partition name of CLR_BOOT will cause it to be re-used. The clear linux os entries should have a different directory from other OSes, so it should be safe.

@bktan8 has added Clear Linux OS to an existing Windows installation both with adding a second EFI partition as well as reusing the existing Windows one. He might provide more details.

**Comment by chdslv** [comment]
I believe, the installer should handle booting options. Most people have Windows and few Linuxes in their systems, and wouldn't want anything to happen to them. So, at least it should ave an option not to install the boot loader. Also, the swap should be a file, rather than a partition. As people already have Grub in their systems, they'd just upgrade the grub and it'd find CL. The CLR_BOOT should not be destructive. People would try CL could be installed alongside on to a dedicated partition.

**Comment by mdhorn** [comment]
@chdslv 
Clear Linux* OS uses systemd-boot for a boot manager, not Grub. There have been discussions about supporting other boot methodologies in [clr-boot-manager](https://github.com/clearlinux/clr-boot-manager); that is the right location to discuss support different/new boot methodologies.

When you say "at least it should have an option not to install the boot loader", are you referring to the creation of a partition for the EFI?  If so, then that option is available to you via Advanced disk configuration by adding the partition name CLR_BOOT onto your existing EFI file system. This should not be destructive as stated earlier each OS has its own hierarchy. If you have such a case, please one a new issue with steps to reproduce so we can investigate and fix a bug.

The request for a swap file as an option instead of a swap partition is already being tracked here:
https://github.com/clearlinux/clr-installer/issues/205
Please follow that GitHub Issues for updates.

Admittedly dual booting with Clear Linux OS is not seamless at the moment, but there are good examples of how to dual boot Windows.
https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-win.html

**Comment by mdhorn** [comment]
The items which can be addressed in the installer I believed have been answered.
Also there ongoing community forum thread regarding this as well:
https://community.clearlinux.org/t/how-to-install-clear-linux-to-separate-partition-without-installing-the-boot-loader/

Closing this issue.
