### ISSUE TITLE
Not bootable after installation

### ISSUE THREAD

**Issue by DasJott** [clearlinux/clr-installer#605]
**Describe the bug**
Not possible to choose Clear Linux in an existing boot menu after successful installation.

**To Reproduce**
1. Having an Arch Linux installed
2. Install Clear Linux on a different partition
3. reboot
4. See the unchanged boot menu only providing Arch - just as before.

**Expected behavior**
I installed Clear Linux to actually use it. But that seems not to be possible.

I spent several hours to find out, why Clear Linux behaves that strange.
That is a very bad experience and I tend to overwrite it again.

**Comment by mdhorn** [comment]
What installation mode did you select? 
Can you share the /root/clr-installer.log and the /root/clr-install.yaml file?
How are you booting Arch?

Clear Linux OS boots using Syslinux in UEFI mode.
The Clear Boot Manager project is working on changes that may support other booting methods.
https://github.com/clearlinux/clr-boot-manager

**Comment by lebensterben** [comment]
For reference: https://community.clearlinux.org/t/not-bootable-after-installation/2194

**Comment by mdhorn** [comment]
Closing due to no feedback from the submitter.
Please refer to the tutorials on Multi-boot for Clear Linux OS 
https://docs.01.org/clearlinux/latest/tutorials/multi-boot/dual-boot-linux.html

If you still are having a problem with multi-boot, please open a new issue for the distribution.
https://github.com/clearlinux/distribution/issues

If you believe there is a bug in the installer or we need to add a new enhancement to the installer, please open a new issue here.
