### ISSUE TITLE
`SQUASHFS error: unable to read id index table` and `end kernel panic`

### ISSUE THREAD

**Issue by sn99** [clearlinux/clr-installer#620]
**Describe the bug**
The setup hits end kernel panic

**To Reproduce**
Selection `Clear Linux OS` to install

**Expected behavior**
Complete the installation

**Screenshots**
![image457](https://user-images.githubusercontent.com/42946112/70238219-dd129980-178e-11ea-8af8-379aa1eb06fd.jpeg)

**Environment (please complete the following information):**
 - Clear Linux OS Version: 31770-live-desktop-iso
 - Installer Version [clr-installer -v]
 - Platform: hp 840 g2

**Comment by mdhorn** [comment]
@sn99 This is usually a symptom of the ISO not being burned properly to the USB media or not properly synced before ejecting.
We validate that these images boot before posting, and I just tested it again.

Could you please verify that the checksum is correct and reflash the image to the USB media?
Ideally, you should follow one of our documented methods:
https://docs.01.org/clearlinux/latest/get-started/bootable-usb.html

If you are using another method, and it still fails, please share your process.

**Comment by sn99** [comment]
I reverted to a previous release, it works fine now, thanks

**Comment by mvincerx** [comment]
I encountered a failed checksum when I downloaded and tested current release of live-desktop: 
- clear-32030-live-desktop.iso-SHA512SUMS
- clear-32030-live-desktop.iso-SHA512SUMS.sig
- clear-32030-live-desktop.iso
Downloaded files from here: https://clearlinux.org/downloads

I encountered this error while testing other dd commands to burn the clear iso--and I wanted to root cause the error.  I also tested the clearlinux-live-server, from same link above, and it had NO errors. 
I'm happy to be wrong about this, but I wanted to bring it to your attention in case of a failed iso. 
Please advise.
@jwakre, @mbelluzzo, @bktan8

**Comment by mdhorn** [comment]
@mvincerx 
- For future issues, please avoid adding to Closed Issue unless we know the original problem was not fixed correctly and needs to be re-opened.
I just download the same images and checksum from https://clearlinux.org/downloads and they matched:

```
# cat clear-32030-live-desktop.iso-SHA512SUMS
949a9f75344f6326beded588021cec9b10963056eadedf8ef4caae0c1afee2f00823b76826936ded466fb79d67987d396e44d827ba2ef179beaa753865fc1504  clear-32030-live-desktop.iso
# sha512sum clear-32030-live-desktop.iso
949a9f75344f6326beded588021cec9b10963056eadedf8ef4caae0c1afee2f00823b76826936ded466fb79d67987d396e44d827ba2ef179beaa753865fc1504  clear-32030-live-desktop.iso
```

**Comment by mvincerx** [comment]
Yes, will do. Glad to hear that they matched. I will show you what I encountered per the docs.

**Comment by mbelluzzo** [comment]
Same for me: 
[mbelluzz@mbelluzz-nuc-00 tmp]$ sha512sum -c ./clear-32030-live-desktop.iso-SHA512SUMS 
clear-32030-live-desktop.iso: OK

So I guess the checksum did its job there. You probably had a flawed download.
