### ISSUE TITLE
Can't scroll to see messages output during an install

### ISSUE THREAD

**Issue by dbkinder** [clearlinux/clr-installer#99]
As noted in #98, the progress display messages showing the final part of the installation can produce enough output that the text scrolls off the screen, but there's no way to scroll back to see what was output.  In this particular case, some warnings were generated and I wanted to see if there were others, but no scrolling option was available. 

**To Reproduce**
See the steps in #98.  (I had selected all the available extra bundles as part of my manual install so LOTS of "progress dots" were written to the screen and many packages were installed.  Curiously, the "progress dots" appeared all at once instead of a few dots every once in a while during the download/install.

**Comment by mdhorn** [comment]
@dbkinder This problem was fixed in the 1.0.0 release in two ways, 1) by no longer printing debug messages by default (a requirement for release), and 2) in that we now cache repeated lines and only print a lint with a line count.

When you can, please confirm this issue is resolved in the 1.0.0 (or later) release as you expected.
The 1.0.0 clr-installer is available via swupd by installing the 'clr-installer' bundle.

If the issue wasn't resolved as expected, please re-open this Issue.
